FROM nginx:1.27-alpine

WORKDIR /var/www

COPY public /var/www/public
COPY docker/nginx/laravel.prod.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/storage/app/public \
    && ln -s /var/www/storage/app/public /var/www/public/storage

