name: Testes do Sistema

on:
  push:
    branches: ["**", "!main", "!develop"]
  workflow_run:
    workflows: ["Teste de Build no Docker"]
    types: [completed]
    branches: [main, develop]

jobs:
  run_tests:
    runs-on: ubuntu-latest
#     if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
          # ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Build Docker Compose and Start Services
        run: docker compose up -d --build

      # - name: Fix permissions
      #   run: docker compose exec -T --user root app chmod -R 777 /var/www

      - name: Composer Install
        run: docker compose exec -T app composer install --no-interaction --prefer-dist

      - name: Test PHP Artisan
        run: docker compose exec -T app php artisan --version

#       - name: Prepare .env
#         run: |
#           docker compose exec -T app cp .env.example .env
#           docker compose exec -T app php artisan key:generate

      - name: Generate app key
        run: docker compose exec -T app php artisan key:generate

#       - name: Wait for MySQL
#         run: |
#           timeout 60 bash -c 'until docker compose exec -T db mysqladmin ping -h localhost --silent 2>/dev/null; do
#             echo "aguardando MySQL..."
#             sleep 3
#           done'
#           echo "MySQL pronto!"

      - name: Run migrations
        run: docker compose exec -T app php artisan migrate --force

      - name: Run tests
        run: docker compose exec -T app php artisan test

      - name: Tear down
        if: always()
        run: docker compose down -v --remove-orphans
