name: Testes do Sistema

on:
  push:
    branches: ["**", "!main", "!develop"]
  workflow_run:
    workflows: ["Teste de Build no Docker"]
    types: [completed]
    branches: [main, develop]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /var/www

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      
      - name: Build Docker Compose and Start Services
        run: docker compose up -d --build

      - name: Configure Git Safe Directory in Container
        run: docker compose exec -T app git config --global --add safe.directory /var/www

      - name: Composer Install
        run: docker compose exec -T app composer install
      
      - name: Test PHP Artisan
        run: docker compose exec -T app php artisan --version
      
      - name: Run migrations
        run: docker compose exec -T app php artisan migrate --force
      
      - name: Run tests
        run: docker compose exec -T app php artisan test
      
      - name: Tear down
        if: always()
        run: docker compose down -v --remove-orphans